title = "yoons.io"

baseURL = "https://yoons.io"
languageCode = "en-us"
theme = "sidemin"
copyright = "(c) 2018 Sick Yoon"
paginate = 6

[author]
  name = "Sick Yoon"
  email = "iam@yoons.io"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Gopher"
  sidebar = true

disableLiveReload = true